"""Remove field first name, last name, add username

Revision ID: 5d3829e8026f
Revises: 5c287b9d4bcb
Create Date: 2025-04-26 22:32:38.750298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d3829e8026f'
down_revision: Union[str, None] = '5c287b9d4bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))

    op.execute('''
            UPDATE "user"
            SET username = 'user_' || id
            WHERE username IS NULL
        ''')

    op.alter_column('user', 'username', nullable=False)

    op.create_unique_constraint('uq_user_username', 'user', ['username'])

    op.drop_column('user', 'first_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
