"""Refactor a complaint table.Add new column

Revision ID: 640f0b4748b3
Revises: 8efdf4ede290
Create Date: 2025-05-01 21:40:09.123365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '640f0b4748b3'
down_revision: Union[str, None] = '8efdf4ede290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('complaint', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('complaint', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('complaint', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'description')
    op.drop_column('complaint', 'longitude')
    op.drop_column('complaint', 'latitude')
    op.drop_column('complaint', 'image_url')
    # ### end Alembic commands ###
