"""Delete column priority in complaint table

Revision ID: 8efdf4ede290
Revises: e9429672b255
Create Date: 2025-05-01 13:38:10.552959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8efdf4ede290'
down_revision: Union[str, None] = 'e9429672b255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
