"""Delete all data

Revision ID: c4d19b27d01c
Revises: d321f9b79ad9
Create Date: 2025-05-06 16:10:37.854858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4d19b27d01c'
down_revision: Union[str, None] = 'd321f9b79ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    conn.execute(sa.text("SET session_replication_role = 'replica';"))

    conn.execute(sa.text("DELETE FROM comments"))
    conn.execute(sa.text("DELETE FROM complaint"))
    conn.execute(sa.text('DELETE FROM "user"'))

    conn.execute(sa.text("SET session_replication_role = 'origin';"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
