"""Delete last_name field

Revision ID: daf9c14635b2
Revises: 5d3829e8026f
Create Date: 2025-04-27 23:43:07.338730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'daf9c14635b2'
down_revision: Union[str, None] = '5d3829e8026f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
